apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "navitain.fullname" . }}
  labels:
    {{- include "navitain.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "navitain.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "navitain.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "navitain.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
