apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "navitain.serviceAccountName" . }}
  labels:
    {{- include "navitain.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-updater
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-updater
subjects:
- kind: ServiceAccount
  name: {{ include "navitain.serviceAccountName" . }}
  namespace: default
