apiVersion: v1
kind: Service
metadata:
  name: {{ include "audio-latency-tracker.fullname" . }}
  labels:
    {{- include "audio-latency-tracker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None  # Headless service for DaemonSet
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "audio-latency-tracker.selectorLabels" . | nindent 4 }}