apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-secret
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echo-secret-app
  template:
    metadata:
      labels:
        app: echo-secret-app
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'echo "hello world"']
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
      containers:
      - name: flask-app
        image: "{{ .Values.flask.repository }}:{{ .Values.flask.tag }}"
        env:
        - name: MY_ENV_CONFIG_1
          value: "val1"
        - name: MY_ENV_CONFIG_2
          value: "val2"
        - name: MY_ENV_CONFIG_3
          value: "val3"
        - name: MY_ENV_CONFIG_4
          value: "val4"
        - name: MY_ENV_CONFIG_5
          value: "val5"
        - name: MY_ENV_CONFIG_6
          value: "val6"
        - name: MY_ENV_CONFIG_7
          value: "val7"
        - name: MY_ENV_CONFIG_8
          value: "val8"
        - name: MY_ENV_CONFIG_9
          value: "val9"
        - name: MY_ENV_CONFIG
          value: "I am from the yaml."
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MY_SECRET_MESSAGE
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
      - name: nginx-sidecar
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
